### ISSUE TITLE
Nightly email reports

### ISSUE THREAD

**Issue by mfleming** [nyrkio/nyrkio#2]
A core hypothesis for nyrkiö is that most users will want to be notified whenever change points are detected rather than and manually logging into the web app and looking at the dashboards. Users should be able to enable nightly reports via some setting on a profile page.

## Open questions
1. How do we want to handle reporting about the same change points? For instance, if we detect a change point for a commit on day N, should we include that change point in every report for day N + 1, N + 2, ... etc? In the past we've "cropped" change points after 7 days to reduce the noise. Should we do the same?
2. Does it actually make sense to report if there are no change points? This is how the current hunter code works -- you'll get an email that says "Hunter did not detect any change points". Maybe yes if we hit the API endpoint but no if it's the period job running.
3. Should we allow users to generate reports for their results on demand? This is currently available via the `/v0/report` endpoint but might allow users to DoS our email provider and disrupt the email reporting mechanism for all users. We probably need some rate limiting in the future but can skip this problem for now.

 ## Overview of changes required
1. Flesh out the nascent `/v0/user/config` endpoint which allows user's to configure their account. We will need validation of nightly email config.
2. Need to add minimal user profile pages. Can just have the one option for nightly reports for now.
3. Some internal periodic job that finds all users that have opted in to nightly reports and computes change points for all their tests and sends an email to their login email address if change points are found
4. Currently we only send email to `matt@nyrk.io`. This needs to be the user's registered email address.
5. The author of the reports needs to be something like `bot@nyrk.io` and not `matt@readmodwrite.com`. We may need a new postmark account?

## Testing
1. We can use the existing data for rocksdb or tigerbeetle, which already has change points, and forcibly trigger the email reporting via the `/v0/report` endpoint.
2. https://github.com/nyrkio/gh-scripts contains a `replay-commits` [script](https://github.com/nyrkio/gh-scripts/blob/main/replay-commits) (currently only for the rocksdb repo) that will cause CircleCI jobs to execute for every commit between a local HEAD and the upstream HEAD for the main branch. This is a long-term test which we can configure and leave running for a few weeks. My assumption is that this will be the most similar to how users will do this in real life.

## Future enhancements
- Configure reporting at the organisation level
- Configure reporting per-project (users may not want to get notifications for toy or dummy projects)
- Rate limiting calls to `/v0/report`
- Embed urls in the email so that users can click and be take straight to `http://nyrk.io` with the dashboard displayed.

**Comment by mfleming** [comment]
Closing as unwanted for now. Can always reopen later.

**Comment by henrikingo** [comment]
Email reports are unwanted? :-D

Can someone take me back to the 90s please ...
