### ISSUE TITLE
Pre-compute change points to reduce web query latency

### ISSUE THREAD

**Issue by mfleming** [nyrkio/nyrkio#3]
This idea has been batted around in the past but every time we discussed it we thought that A) the change point computation was so fast we could do it in real-time and B) users want the ability to change the magnitude on the fly which necessitates real-time change point computation anyway.

However, I think we should reassess. A quick profile reveals that the majority of the web query latency (e.g. `GET /index`) goes to computing change points. We're talking around 76% of the time when accessing `/index` for the rocksdb data set. By comparison, only 20% is spent accessing the DB to gather the data required for change point computation.

![flame](https://github.com/nyrkio/nyrkio/assets/94254/818a28a3-c0ed-407d-925e-e6dc86977abb)

Single query latency with no concurrency is currently sitting around 1.9secs for this dataset.

```
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking nyrk.io (be patient)
Finished 16 requests


Server Software:        nginx/1.25.3
Server Hostname:        nyrk.io
Server Port:            80

Document Path:          /index
Document Length:        761838 bytes

Concurrency Level:      1
Time taken for tests:   31.403 seconds
Complete requests:      16
Failed requests:        0
Total transferred:      12197568 bytes
HTML transferred:       12189408 bytes
Requests per second:    0.51 [#/sec] (mean)
Time per request:       1962.688 [ms] (mean)
Time per request:       1962.688 [ms] (mean, across all concurrent requests)
Transfer rate:          379.32 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       19   20   1.1     20      23
Processing:  1695 1942 138.2   1961    2199
Waiting:     1477 1701 135.1   1722    1962
Total:       1714 1963 138.1   1980    2219

Percentage of the requests served within a certain time (ms)
  50%   1980
  66%   1990
  75%   2061
  80%   2061
  90%   2192
  95%   2219
  98%   2219
  99%   2219
 100%   2219 (longest request)
```

Additionally, this has implications for scaling and the hardware that we need to use for Nyrkiö. If our workload remains CPU-bound then we'll need much larger machines to handle multiple concurrent users or larger data sets.

## Two options

The way I see it, we only really have two options unless we want to throw hardware at the problem which we don't because I don't think it's important enough to the business that we just throw money at it.

1. Rewrite the Hunter significance testing code **AND** the E-divisive algorithm in a faster language like rust or C++
2. Pre-compute change points so the latency of `GET /index` is dominated by I/O in the form of a DB query

To be clear, 2. can also include computing change points in real-time as soon as the user toggles the magnitude/pvalue sliders. But the majority of users will probably set this once (when we can configure this per-user/project/testrun) and simply want to read the results thereafter so we can provide a really fast initial page load.

**Comment by henrikingo** [comment]
Wait, how did this fix itself?

Also, what I really wanted to say is that in the MongoDB implementation Jim O'leary did implement the computation parts in C++, and it yielded about a 10x improvement. I hadn't realized Piotr didn't build upon that for Hunter?
