### ISSUE TITLE
Navigating to a non-existent test should warn user

### ISSUE THREAD

**Issue by mfleming** [nyrkio/nyrkio#62]
If you type in a url for a non-existent test you don't currently get any indication that the url is invalid. We should warn the user with a "no such test" or even a 404 would be better than what we have right now.

![image](https://github.com/nyrkio/nyrkio/assets/94254/53b567ad-18b4-45c1-b3bb-052982a86693)

**Comment by henrikingo** [comment]
IMO 404 is exactly what should happen

**Comment by mfleming** [comment]
This is actually fixed for the `/result/` paths but not for `/tests/`, e.g.

![image](https://github.com/nyrkio/nyrkio/assets/94254/6a9431b3-3f2c-4ff6-b57b-61bbb7de7e99)
